Repository SenteraLLC/ulabel, pull requests merged in 2022-06, with the labels that each got.

#69 another deprecation fix
  dist/ulabel.js
  src/toolbox.js
  src/toolbox.ts
Labels: bug

#72 New configuration
  dist/ulabel.js
  src/configuration.js
  src/configuration.ts
  src/index.js
  src/toolbox.js
  src/toolbox.ts
Labels: refactor

#74 Can now use keypoint slider functionality without moving keypoint slider
  dist/ulabel.js
  src/toolbox.js
  src/toolbox.ts
Labels: refactor

#77 On load check for annotation size cookie or config default
  dist/ulabel.js
  src/configuration.js
  src/configuration.ts
  src/toolbox.js
  src/toolbox.ts
Labels: enhancement

#78 better edit candidates
  demo/multi-class.html
  dist/ulabel.js
  src/index.js
Labels: bug

#80 Fixed KeypointSliderItem passing in incorrect parameter
  dist/ulabel.js
  src/toolbox.js
  src/toolbox.ts
Labels: bug

#81 Added buttons and keybinds to increment and decrement keypoint slider value
  dist/ulabel.js
  src/blobs.js
  src/configuration.js
  src/configuration.ts
  src/toolbox.js
  src/toolbox.ts
Labels: enhancement

#82 Change css styling
  dist/ulabel.js
  src/blobs.js
Labels: enhancement

#83 Vanish all
  dist/ulabel.js
  index.d.ts
  src/toolbox.js
  src/toolbox.ts
Labels: enhancement

#84 Delete on hover
  dist/ulabel.js
  src/configuration.js
  src/configuration.ts
  src/index.js
Labels: enhancement
