Repository SenteraLLC/ulabel, pull requests merged in 2023-05, with the labels that each got.

#107 Fix issue with no default toolbox order supplied.
  dist/ulabel.js
  dist/ulabel.min.js
  dist/ulabel.min.js.LICENSE.txt
  package-lock.json
  package.json
  src/configuration.ts
  src/index.js
  src/version.js
  webpack.config.js
Labels: bug

#108 Filter distance from row update
  demo/row-filtering-example.html
  dist/ulabel.js
  dist/ulabel.min.js
  index.d.ts
  package.json
  src/annotation_operators.ts
  src/configuration.ts
  src/index.js
  src/toolbox.ts
  src/version.js
Labels: bug, enhancement

#109 Add Keybind to Create BBox Annotation Around Initial Crop
  demo/row-filtering-example.html
  dist/ulabel.js
  dist/ulabel.min.js
  package.json
  src/configuration.ts
  src/index.js
  src/subtask.ts
  src/version.js
Labels: enhancement

#110 Add Ability To Set Default Filter Distance Value On Load
  dist/ulabel.js
  dist/ulabel.min.js
  package.json
  src/configuration.ts
  src/index.js
  src/toolbox.ts
  src/version.js
Labels: enhancement
