Repository SenteraLLC/ulabel, pull requests merged in 2024-05, with the labels that each got.

#144 [WS-646] [WS-680] [WS-687] Fix/recenter keybind
  changelog.md
  dist/ulabel.js
  dist/ulabel.min.js
  package.json
  src/index.js
  src/toolbox.ts
  src/version.js
Labels: bug

#145 Feature/remove event listeners
  api_spec.md
  changelog.md
  dist/ulabel.js
  dist/ulabel.min.js
  package-lock.json
  src/html_builder.ts
  src/index.js
  src/toolbox.ts
Labels: bug, enhancement

#147 [WS-779] [WS-786] Fix/class switch
  changelog.md
  demo/resume-from.html
  dist/ulabel.js
  dist/ulabel.js.LICENSE.txt
  dist/ulabel.min.js
  dist/ulabel.min.js.LICENSE.txt
  index.d.ts
  package-lock.json
  package.json
  src/index.js
  src/toolbox.ts
  src/version.js
Labels: bug, QA Complete

#149 Fix bugs with how dialogs are handled
  changelog.md
  dist/ulabel.js
  dist/ulabel.min.js
  package.json
  src/index.js
  src/version.js
Labels: bug

#150 [WS-793] fix/delete-mode-cancel
  changelog.md
  dist/ulabel.js
  dist/ulabel.min.js
  package-lock.json
  package.json
  src/index.js
  src/version.js
Labels: bug

#152 Fix/memory usage
  changelog.md
  dist/ulabel.js
  dist/ulabel.min.js
  package-lock.json
  package.json
  src/annotation.ts
  src/index.js
  src/toolbox.ts
  src/version.js
Labels: bug, refactor
