Repository SenteraLLC/ulabel, pull requests merged in 2024-09, with the labels that each got.

#160 Fix/more event listeners
  api_spec.md
  changelog.md
  dist/ulabel.js
  dist/ulabel.min.js
  package-lock.json
  package.json
  src/index.js
  src/version.js
Labels: bug

#161 doc/158 update api spec
  api_spec.md
  changelog.md
  dist/ulabel.js
  dist/ulabel.min.js
  index.d.ts
  package-lock.json
  package.json
  src/configuration.ts
  src/version.js
Labels: bug, documentation

#163 [PLAT-453] feature/submit css
  api_spec.md
  changelog.md
  demo/multi-class.html
  dist/ulabel.js
  dist/ulabel.min.js
  index.d.ts
  package-lock.json
  package.json
  src/blobs.js
  src/index.js
  src/toolbox.ts
  src/version.js
Labels: bug, enhancement

#167 [PLAT-476] Fix/sliders
  api_spec.md
  changelog.md
  demo/resume-from.html
  demo/row-filtering-example.html
  dist/ulabel.js
  dist/ulabel.min.js
  index.d.ts
  package-lock.json
  package.json
  src/annotation.ts
  src/annotation_operators.ts
  src/configuration.ts
  src/index.js
  src/overlays.ts
  src/toolbox.ts
  src/utilities.ts
  src/version.js
Labels: bug, enhancement

#169 Add README section on react integration
  README.md
Labels: documentation

#170 Refactor/config
  api_spec.md
  changelog.md
  demo/multi-class.html
  demo/row-filtering-example.html
  dist/ulabel.js
  dist/ulabel.min.js
  index.d.ts
  package-lock.json
  package.json
  src/annotation_operators.ts
  src/configuration.ts
  src/index.js
  src/toolbox.ts
  src/version.js
Labels: bug, documentation, refactor
